add new model
sort-font/webpage pull request #12
Opened 2021-07-24 09:21 UTC by monarsan

## 概要
モデルを修正した
ファイル名も修正した
## なぜ必要なのか
以前のモデルは完全でないデータセットを使って学習させていたため、今回修正した。
それに伴って、長いファイル名を簡潔にした。

2021-07-24 13:17 UTC, task4233 requested changes
このままだと起動しないので修正をお願いします！

2021-07-24 13:17 UTC, task4233 commented on model.py
> +with open("model_.model", 'r') as f:
typoしてる気がします

```suggestion
with open("model.model", 'r') as f:
```

2021-07-24 13:22 UTC, task4233 commented on model.py
>  with open("list_row.txt", "rb") as f:
前から思っていたのですが、`list_row.txt`はpickleファイルなので拡張子を`.pkl`にした方がいいと思います。

2021-07-26 12:06 UTC, monarsan commented on model.py
>  with open("list_row.txt", "rb") as f:
修正しました

2021-07-26 12:07 UTC, monarsan commented
シェルスクリプトはimagesの中身の画像を消すためのものです。macなら動くはず。

2021-07-26 12:21 UTC, task4233 commented
シェルスクリプトを書くくらいなら下記のようなMakefileを書いた方がいい気がしました。

```Makefile
run:
    python3 server.py

clean:
    rm -rf static/images/
    mkdir -p static/images/
```

2021-07-26 12:22 UTC, task4233 commented on model.py
>  with open("list_row.txt", "rb") as f:
Pythonプログラムの方は修正されていたのですが、実際のファイルが修正されていないようです。

2021-07-26 12:40 UTC, monarsan commented on model.py
>  with open("list_row.txt", "rb") as f:
add するの忘れてました、、

2021-07-26 13:56 UTC, task4233 reviewed
Makefileを追加してrmfile.shが必要なくなったので、そちらは削除してしまいますね

2021-07-26 14:02 UTC, task4233 approved these changes
ローカルで動かした際に、異なるフォントが表示されることを確認しました！
何度も修正していただきありがとうございました！

2021-07-26 14:02 UTC, merged